### ISSUE TITLE
Glaring bug: Klingon is missing.

### ISSUE THREAD

**Issue by christophberger** [pemistahl/lingua-go#1]
butlhghajboghnuv'e'eyIHo'.

**Comment by pemistahl** [comment]
Haha, well, let's concentrate on earthly languages first, ok? I doubt that alien races are much interested in language detection. At least, they have not been able to tell us yet. ;-)

**Comment by christophberger** [comment]
Sure, sounds like solid prioritization. 

But maybe you want at least give a thought to detecting [Vogon poetry](https://en.wikipedia.org/wiki/Vogon#Poetry) - this could be life-saving... 😁
