### ISSUE TITLE
Find more memory-efficient data structure for language models

### ISSUE THREAD

**Issue by pemistahl** [pemistahl/lingua-go#18]
Currently, the language models are loaded into simple maps at runtime. Even though accessing the maps is pretty fast, they consume a significant amount of memory. The goal is to investigate whether there are more suitable data structures available that require less storage space in memory, something like NumPy for Python.

One promising candidate could be [Gonum](https://www.gonum.org/).

**Comment by goldsam** [comment]
I think you will benefit from using a [trie](https://en.m.wikipedia.org/wiki/Trie#:~:text=In%20computer%20science%2C%20a%20trie,key%2C%20but%20by%20individual%20characters.) (not tree) data structure. [Here is a Go implementation you may be able to use as a drop in replacement to `map`](https://github.com/dghubble/trie/blob/main/rune_trie.go).

**Comment by TomDeneire** [comment]
I wonder if using a SQLite database to store your frequencies would help. That way you would only need to open a database connection and not load full frequency maps into memory. With indexing and query optimization (SQL could handle a piece of the logic of determining the highest frequency) it seems to me it would be pretty fast and very low memory footprint.

**Comment by pemistahl** [comment]
Closed in favor of #68.
