### ISSUE TITLE
`go get` error: `unknown revision serialization/v1.2.0`

### ISSUE THREAD

**Issue by BenStigsen** [pemistahl/lingua-go#23]
I hope this is related to the library and not something with my Go installation.

When I run: `go get github.com/pemistahl/lingua-go`
I get the following error:
```
go: downloading github.com/pemistahl/lingua-go/serialization v1.2.0
github.com/pemistahl/lingua-go imports
        github.com/pemistahl/lingua-go/serialization: reading github.com/pemistahl/lingua-go/seriali
zation/go.mod at revision serialization/v1.2.0: unknown revision serialization/v1.2.0
```

**Comment by pemistahl** [comment]
I'm sorry, there is a obviously something wrong in one of the library's `go.mod` files. I will fix it later this day.

**Comment by pemistahl** [comment]
Fixed and closed. :)
