### ISSUE TITLE
Could not add the package to project(403 Forbidden)

### ISSUE THREAD

**Issue by soshika** [pemistahl/lingua-go#24]
Hello

I could not add package to my project when i use command below 
`go get github.com/pemistahl/lingua-go`

i got this error
go: downloading github.com/pemistahl/lingua-go v1.2.1
go: github.com/pemistahl/lingua-go@v1.2.1: reading https://proxy.golang.org/github.com/pemistahl/lingua-go/@v/v1.2.1.zip: 403 Forbidden

**Comment by pemistahl** [comment]
Hi @soshika, this error has nothing to do with my library. HTTP 403 means the server understands your request but refuses to authorize it. I can only guess the reason. Perhaps it's just a temporary problem. Or the server blocks all requests from Iran. I don't know. You can try to use a VPN and see if the download succeeds then.

**Comment by soshika** [comment]
@pemistahl oh I see. thanks .
