### ISSUE TITLE
Library size optimization

### ISSUE THREAD

**Issue by jeffphp** [pemistahl/lingua-go#26]
Thanks for this very efficient library (it's the best I've tested so far).

Unfortunately, I struggle with its size, because whatever parameters I choose, it keeps adding around 120MiB to my app (which is 50MiB, assets included). Since I am using Kubernetes, the docker image matters.

I am only interested in checking a few languages, but it seems that whatever language (or options I choose), the whole package is still compiled. May be I miss something ...

If not, it would be nice to be able to provide the languages as imports (lingua.English, ..., lingua.Languages) in order to keep the binary small.

**Comment by pemistahl** [comment]
Hi Jeff, thank you for the nice words. :) I'm happy that my library is as useful to you as I hoped it would be.

All language models are embedded into the compiled binary for convenience. Unfortunately, Go does not (yet) support conditional embedding which could solve your problem.

I suggest the following (untested but should work):
1. Clone this repository to your local computer.
2. Remove all language models you don't need from the directory [`language-models`](https://github.com/pemistahl/lingua-go/tree/main/language-models).
3. Build the binary manually and add it to your Docker image.
4. During runtime, build the language detector from the exact set of languages you need. This way, the detector won't try to access the language model files you have removed.

Please let me know whether this approach works for you.

**Comment by jeffphp** [comment]
Excellent idea, thanks for that. I will definitely try to do this and let you know how it goes!

**Comment by pemistahl** [comment]
Glad to know that my approach works for you. :)

Having each language as a separate module is possible, of course, but pretty cumbersome in Go. I think I won't follow this approach for this library. It would be great if Go supported conditional compilation in the same way as Rust does. Maybe, some day...

**Comment by aimuz** [comment]
https://github.com/aimuz/lingua-go/tree/simplify

I forked this branch and used a generation command for easier maintenance.       

```go
package main

import (
	"fmt"
	"os"
)

func main() {
	dirs, err := os.ReadDir("language-models")
	if err != nil {
		fmt.Printf("Failed to read the "language-models" directory: %v\n", err)
		os.Exit(1)
	}

	for _, dir := range dirs {
		if !dir.IsDir() {
			continue
		}

		langCode := dir.Name()
		dirPath := fmt.Sprintf("language-models/%s", langCode)
		
		filePath := fmt.Sprintf("%s/embed.go", dirPath)
	
		content := fmt.Sprintf(`package %s

import (
	"embed"
	"github.com/pemistahl/lingua-go"
)

//go:embed *.zip
var model embed.FS

func init() {
	lingua.Register("%s", model)
}
`, langCode, langCode)
		err = os.WriteFile(filePath, []byte(content), 0644)
		if err != nil {
			fmt.Printf("Failed to write to file %s: %v\n", filePath, err)
			continue
		}
	}
}
```

By the following means, my program has been significantly reduced from 138MB to 31MB.

```go
import (
	"github.com/pemistahl/lingua-go"
	_ "github.com/pemistahl/lingua-go/language-models/ar"
	_ "github.com/pemistahl/lingua-go/language-models/de"
	_ "github.com/pemistahl/lingua-go/language-models/en"
	_ "github.com/pemistahl/lingua-go/language-models/es"
	_ "github.com/pemistahl/lingua-go/language-models/fr"
	_ "github.com/pemistahl/lingua-go/language-models/it"
	_ "github.com/pemistahl/lingua-go/language-models/ja"
	_ "github.com/pemistahl/lingua-go/language-models/ko"
	_ "github.com/pemistahl/lingua-go/language-models/pt"
	_ "github.com/pemistahl/lingua-go/language-models/ru"
	_ "github.com/pemistahl/lingua-go/language-models/zh"
)
```

Maybe we can use a similar approach in v2. Using generate to maintain the code won't add much complexity. Then we can also add an "all pkg" so that users can easily embed all models.

**Comment by asciimoo** [comment]
@pemistahl First of all, thank you for the great project. Let me share my opinion on this topic:

> All language models are embedded into the compiled binary for convenience.

That's a nice convenience feature, however it shouldn't be the default. There could be individual language based packages and an `"all"` package that imports all the language packages and provides the current convenience API. This way it would be possible to enjoy the currently provided API while having the ability to include only necessary languages to our binaries.

> Remove all language models you don't need from the directory language-models.

This approach assumes that there is only one project using `lingua-go`. Having even one project that requires all the supported languages makes it impossible to delete from `lingua-go` without reinstalling `lingua-go` every time building a different project - even if other projects are using only one language.

> Go does not (yet) support conditional embedding which could solve your problem.

No conditional embedding required in my opinion, just a bit more nuanced package usage.

What do you think?
