### ISSUE TITLE
I tested with a long italian text but the output is "17" which is English. How to make it work correctly?

### ISSUE THREAD

**Issue by raphael10-collab** [pemistahl/lingua-go#59]
I tested the adaptation of the `basic.go` for calling the golang function from a c-code:

    package main
    
    import "C"
    
    import (
            "fmt"
            "github.com/pemistahl/lingua-go"
    )
    
    var lan lingua.Language
    
    //var lan int
    
    //export Langdetectfunct
    func Langdetectfunct(text *C.char) int {
    
        textS := C.GoString(text);
    
        detector := lingua.NewLanguageDetectorBuilder().
            FromAllLanguages().
            Build()
    
        if language, exists := detector.DetectLanguageOf(textS); exists {
            lan = language
        }
        lan = lingua.English
    
        return int(lan)
    
    }
    
    func main() {
        // https://github.com/pemistahl/lingua-go/blob/main/language.go 
    
        testo := "Il liceo classico, noto in passato anche come ginnasio, è una scuola secondaria di secondo grado quinquennale a ciclo unico del sistema scolastico italiano incentrata sugli studi umanistici. Fu istituito come scuola d'élite con la riforma Gentile nel 1923, traendo origini dal ginnasio-liceo>
    
        ctesto := C.CString(testo);
    
        res := Langdetectfunct(ctesto);
        fmt.Println(res)
    }

Despite the Italian text is long, it outputs "17"  which, according to the language codes list here: https://github.com/pemistahl/lingua-go/blob/main/language.go is "English" : 

    raphy@raohy:~/go-lang-detect$ go run basic.go
    17

Why? Did I make any mistake? How to make it work correctly?

**Comment by pemistahl** [comment]
@raphael10-collab Please learn Go first before opening issues hastily. As far as integration with C is concerned, I cannot help you as I'm not a C programmer. Thank you.

**Comment by raphael10-collab** [comment]
@pemistahl Sorry for opening this last issue. I didn't want to bother you so much. But, as you saw, I opened and closed it readily
